config/routes.rb
Rails.application.routes.draw do

  root to: 'services#index'

  resources :services do
  	get "delete"
  end  

  resources :products do
	  get "delete"
	end

  resources :resumes do
    get "delete"
  end

  #match ':controller(/:action(/:id))', :via => [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :service

	def self.to_csv(options = {})
		desired_columns = ["name", "platforms"]
	  CSV.generate(options) do |csv|
	    csv << desired_columns
	    all.each do |product|
	      csv << product.attributes.values_at(*desired_columns)
	    end
	  end
	end

end

app/models/resume.rb
class Resume < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  	validates :name, presence: true # Make sure the owner's name is present.
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :products

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :find_service

  def index
    @products = @service.products
    require 'csv'
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls

      format.pdf do
        render :pdf => "Products", :template => "layouts/pdf.html.erb" # file_name Excluding ".pdf" extension.
      end
    end
  end

  def show
  	@product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @products = Product.where(:service_id => params[:product][:service_id])
  end

  def edit
  	@product = Product.find(params[:id])
    @service = Service.find(@product.service_id)
  end

  def update
    @product = Product.find(params[:id])
  	@product.update_attributes(product_params)
    @products = Product.where(:service_id => params[:product][:service_id])
  end

  def delete
  	@product = Product.find(params[:product_id])
  end

  def destroy
  	@product = Product.find(params[:id]).destroy
    @products = Product.where(:service_id => @product.service_id)
  end

  private
  def product_params
  	params.require(:product).permit(:service_id, :name, :platforms)
  end

  def find_service
    if params[:service_id]
      @service = Service.find(params[:service_id])
    end
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "index"
    end
  end

  def delete
    @resume = Resume.find(params[:resume_id])
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

	private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index
  	@services = Service.all
  end

  def show
  	@service = Service.find(params[:id])
  end

  def new
  	@service = Service.new
  end

  def create
  	@services = Service.all
  	@service = Service.create(service_params)
  end

  def edit
  	@service = Service.find(params[:id])
  end

  def update
  	@services = Service.all
    @service = Service.find(params[:id])
  	@service.update_attributes(service_params)
  end

  def delete
  	@service = Service.find(params[:service_id])
  end

  def destroy
  	@services = Service.all
  	@service = Service.find(params[:id]).destroy
  end

  private
  def service_params
  	params.require(:service).permit(:name, :products)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> 
  <head>
    <title>A</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'paper', href: 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/paper/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <!-- <%= wicked_pdf_image_tag 'mysite.jpg' %> -->
    </div>
    <div id="content">
      <%= yield %>
      <p>Below Yield</p>
    </div>
  </body>
</html>

app/views/products/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Product</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @product.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This product", product_path(@product), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/products/_edit.html.erb
<!--
<div class="modal-header">
  <h3><%= "Editing #{@product.name}" %></h3>
</div>
-->
<% @modal_title = "Edit Product" %>
<%= render "form" %>

app/views/products/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="modal-title"><%= @modal_title%></h3>
    </div>
    <%= form_for @product, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">        
        <ul class="errors"></ul>
        <div class="form-group">
          <%= f.label :service, class:"control-label" %> : 
          <%= @service.name %>
        </div>
        <div class="form-group">
          <%= f.hidden_field :service_id, :value => @service.id, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :name, class:"control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :platforms, class: "control-label" %>
          <%= f.text_field :platforms, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-success" %>
        <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_index.html.erb
<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.platforms %></td>
    <td>
    <%= link_to "Edit", edit_product_path(product), remote: true, class: "btn btn-default" %> 
    <%= link_to "Delete", product_delete_path(product), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/products/_new.html.erb
<!--
<div class="modal-header">
<h3>New Service</h3>
</div>
-->
<% @modal_title = "Create New Product" %>
<%= render "form" %>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= escape_javascript(render 'index') %>")
  $("#product-modal").modal("hide")
<% end %>

app/views/products/create.js.erb
<%= render "save" %>

app/views/products/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/products/destroy.js.erb
<%= render 'save' %>

app/views/products/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/products/index.html.erb
<div class="container">
  <div class="header">
    <div class="cardbtr">
      <h4>Service: <%= @service.name %></h4>
      
      <div style="display: inline-block;"><%= link_to "Back", services_path, class: "btn btn-primary" %></div>  
      <!-- <div class="pull-right"></div> -->
      <div style="display: inline-block; float: right;">
        <%= link_to "New Product", new_product_path(:service_id => @service.id), remote: true, class: "btn btn-primary" %>

        <%= link_to "<span class = 'glyphicon glyphicon-download-alt'></span> PDF file".html_safe, products_path(format: "pdf", service_id: @service.id), class: "btn btn-default", :download => "Products" %> 
        <%= link_to "<span class = 'glyphicon glyphicon-download-alt'></span> CSV file".html_safe, products_path(format: "csv", service_id: @service.id), class: "btn btn-default" %> 
        <%= link_to "<span class = 'glyphicon glyphicon-download-alt'></span> EXCEL sheet".html_safe, products_path(format: "xls", service_id: @service.id), class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <!-- Graph begin-->
  <div id="graph" class="cardbtr graph"></div>
  <script type="text/javascript">
    $(function () {
      $('#graph').highcharts({
          chart: {
              type: 'column'
          },
          title: {
              text: 'Products Portability'
          },
          xAxis: {
              categories: [ "<%= @service.name %>" ]                
          },
          yAxis: {
              title: {
                  text: 'Platforms'
              }
          },
          // series: [{
          //     name: 'Jane',
          //     data: [1, 3, 4]
          // }, {
          //     name: 'John',
          //     data: [5, 7, 3]
          // }],

          series: [
              <% @products.each do |product| %>
                {
                name: '<%= product.name %>',
                data: [                  
                    <%= product.platforms %>,                  
                ]},
              <% end %>
          ],

      });
    });
  </script>
  <!-- Graph end -->
  <div class="cardbtr">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Product</th>
          <th>Platforms</th>
          <td>&nbsp;</td>
        </tr>
      </thead>
      <tbody class="product-index">
        <%= render "index" %>
      </tbody>
    </table>    
  </div>
</div>
<div id="product-modal" class="modal fade"></div>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Platforms Supported</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.platforms %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/products/update.js.erb
<%= render "save" %>

app/views/resumes/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete File</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @resume.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This File", resume_path(@resume), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/resumes/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title"><%= @modal_title%></h4>
    </div>
    <%= form_for @resume, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
        <div class="form-group">
          <!-- <%= f.label :name, class:"control-label" %> -->
          <%= f.text_field :name, :placeholder => "File Name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.file_field :attachment %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Save", class: "btn btn-success" %>
        <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/resumes/_index.html.erb
<% @resumes.each do |resume| %>
	<tr>
	  <td><%= resume.name %></td>
	  <td><%= link_to resume.attachment_identifier, resume.attachment_url %></td>
	  <td><%= link_to '<span class="glyphicon glyphicon-trash"></span> &nbsp; Delete'.html_safe, resume_delete_path(resume), remote: true, class: "btn btn-danger" %></td>
	</tr>
<% end %>

app/views/resumes/_new.html.erb
<!--
<div class="modal-header">
<h3>New Service</h3>
</div>
-->
<% @modal_title = "Upload File" %>
<%= render "form" %>

app/views/resumes/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/resumes/index.html.erb
<div class="container">
  <div class="well cardbtr">
    <%= link_to '<span class="glyphicon glyphicon-upload"></span> Upload'.html_safe, new_resume_path, remote: true, class: "btn btn-primary", 'data-toggle' => "tooltip", 'title' => "Resume" %>
  </div>
  <!--<div class="new-product"></div> -->
  
  <% if !flash[:notice].blank? %>
    <div class="alert alert-info">
    <%= flash[:notice] %>
    </div>
  <% end %>

  <table class="table table-hover cardbtr">
    <thead>
      <tr>
        <th>Name</th>
        <th>Download Link</th>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="product-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="product-modal" class="modal fade"></div>

app/views/resumes/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/services/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Service</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @service.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This service", service_path(@service), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/services/_edit.html.erb
<!--
<div class="modal-header">
  <h3><%= "Editing #{@service.name}" %></h3>
</div>
-->
<% @modal_title = "Edit Service" %>
<%= render "form" %>

app/views/services/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title"><%= @modal_title%></h4>
    </div>
    <%= form_for @service, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
        <div class="form-group">
          <!-- <%= f.label :name, class:"control-label" %> -->
          <%= f.text_field :name, :placeholder => "Service Name", class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-success" %>
        <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/services/_index.html.erb
<% @services.each do |service| %>
  <tr>
    <td><%= service.name %></td>
    <td><%= service.products.size %></td>
    <td>
    <%= link_to '<span class="glyphicon glyphicon-list"></span> View'.html_safe, {:controller => 'products', :service_id => service.id}, class: "btn btn-info", 'data-toggle' => "tooltip", 'title' => "Products" %>
    <%= link_to '<span class="glyphicon glyphicon-edit"></span> &nbsp; Edit'.html_safe, edit_service_path(service), remote: true, class: "btn btn-default" %> 
    <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, service_delete_path(service), remote: true, class: "btn btn-danger", 'data-toggle' => "tooltip", 'title' => "Delete" %>
    </td>
  </tr>
<% end %>

app/views/services/_new.html.erb
<!--
<div class="modal-header">
<h3>New Service</h3>
</div>
-->
<% @modal_title = "Create New Service" %>
<%= render "form" %>

app/views/services/_save.js.erb
$("ul.errors").html("")
<% if @service.errors.any? %>
  <% @service.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= escape_javascript(render 'index') %>")
  $("#product-modal").modal("hide")
<% end %>

app/views/services/create.js.erb
<%= render "save" %>

app/views/services/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/services/destroy.js.erb
<%= render 'save' %>

app/views/services/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/services/index.html.erb
<div class="container">
  <div class="cardbtr">
    <%= link_to '<span class="glyphicon glyphicon-plus"></span> Add'.html_safe, new_service_path, remote: true, class: "btn btn-primary", 'data-toggle' => "tooltip", 'title' => "New Service" %>
  </div>
  <div class="cardbtr">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Products</th>
          <td>&nbsp;</td>
        </tr>
      </thead>
      <tbody class="product-index">
        <%= render "index" %>
      </tbody>
    </table>
  </div>
</div>
<div id="product-modal" class="modal fade"></div>

app/views/services/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/services/update.js.erb
<%= render "save" %>